// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test Main', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test Main', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1260, height: 852 })
    await driver.findElement(By.css("span > a")).click()
    await driver.findElement(By.css(".css-mf2zkt > .css-1bdadyq > .ps-menu-label")).click()
    await driver.findElement(By.css(".ps-submenu-root > .ps-menu-button > .ps-menu-label")).click()
    await driver.findElement(By.css(".ps-menuitem-root:nth-child(1) > .css-ra3y5v > .ps-menu-label")).click()
    await driver.findElement(By.css(".css-mf2zkt:nth-child(2) .ps-menu-label")).click()
    await driver.findElement(By.css(".ps-menuitem-root:nth-child(1) > .css-ra3y5v > .ps-menu-label")).click()
    await driver.findElement(By.css(".css-mf2zkt > .css-1bdadyq > .ps-menu-label")).click()
    await driver.findElement(By.css(".scroll")).click()
    await driver.findElement(By.css(".card:nth-child(10) img")).click()
    await driver.findElement(By.css(".card:nth-child(5) img")).click()
  })
})
